### ISSUE TITLE
Fork and PyPI upload

### ISSUE THREAD

**Issue by flyte** [xerodotc/overdrive-python#1]
Hi, thanks for the library! This is really useful for the project I'm working on.

I've forked your code and made a few changes, mostly to the handling of messages received by the cars. In order to use this library in projects, I've created a [PyPI package](https://pypi.org/project/anki-overdrive/). 

Since I need to get on with my project this week, I'm publishing from my own repository, but as it's mostly your code, would you rather have control of this? It probably makes more sense, because I don't own the Anki kit I'm working with. It can be set up so we can both be listed as owners/collaborators on PyPI now.

Happy to discuss how you want to proceed with this.

Cheers,
Ellis

**Comment by xerodotc** [comment]
Thanks.
I don't own the Anki kit either, so I think I shouldn't assume control over this since I don't have the kit to test with.

Feel free to fork and publish to PyPI from your repos.

**Comment by flyte** [comment]
OK, cheers. Thanks again for the work on this library.
